<?php

/**
 * @file
 * The geolayer_map module.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_theme().
 */
function geolayer_map_theme($existing, $type, $theme, $path) {
  return [
    'geolayer_map' => [
      'variables' => [
        'attributes' => [],
      ],
    ],
  ];
}

/**
 * Implements hook_form_alter().
 */
function geolayer_map_form_alter(&$form,FormStateInterface $form_state, $form_id) {
  // echo $form['#id'];
  // $form['geolayer_map'] = [
  //   '#type' => 'geolayer_map',
  //   '#map_type' => 'default',
  //   '#map_settings' => [
  //     'wkt' => 'POINT(-122.4194 37.7749)',
  //     'geolayers' => 'geolayer_map_default',
  //     'entity_type' => 'node',
  //     'behaviors' => [
  //       'wkt' => [
  //         'zoom' => TRUE,
  //       ],
  //     ],
  //   ],
  //   '#attached' => [
  //     'library' => [
  //       'geolayer_map/geolayer_map'
  //     ],
  //   ],
  // ];

}