---
version: "3.7"

services:

  db:
    image: mariadb:10.10
    restart: unless-stopped
    stop_grace_period: 30s
    environment:
      MYSQL_ROOT_PASSWORD: "${MARIADB_ROOT_PASSWORD:-M4r14DB}"
      MYSQL_DATABASE: "${DB_NAME:-drupal}"
      MYSQL_USER: "${DB_USER:-drupal}"
      MYSQL_PASSWORD: "${DB_PASS:-drupal}"
    labels:
      - traefik.enable=false
      - com.centurylinklabs.watchtower.enable=true
      - docker-volume-backup.stop-during-backup=${BACKUP_STOP_CONTAINER_LABEL:-brms}
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - internal

  drupal:
    image: ${DOCKER_REGISTRY:-docker.tr.utils.nfa.go.ug}/national-forestry-authority/brms:${DRUPAL_IMAGE_TAG:-main}
    #build:
    #  context: .
    depends_on:
      - db
    environment:
      # Overrides Dockerfile defaults
      DB_HOST: db
      PROJECT_BASE_URL: ${HOST_NAME:-}
    restart: unless-stopped
    #ports:
    #  - "${HOST_PORT:-80}:80"
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik
      - traefik.http.routers.${TRAEFIK_ROUTER_NAME:-brms}.rule=Host("${HOST_NAME}")
      - com.centurylinklabs.watchtower.monitor-only=true
    volumes:
      - drupal-files:/var/www/web/sites/default/files
      - drupal-private:/var/www/web/private
    networks:
      - internal
      - traefik

  backup:
    profiles:
      - prod
    image: offen/docker-volume-backup:v2
    restart: always
    environment:
      BACKUP_STOP_CONTAINER_LABEL: ${BACKUP_STOP_CONTAINER_LABEL:-brms}
      AWS_ACCESS_KEY_ID:
      AWS_SECRET_ACCESS_KEY:
      NOTIFICATION_LEVEL:
      NOTIFICATION_URLS:
      BACKUP_CRON_EXPRESSION:
      AWS_ENDPOINT:
      BACKUP_FILENAME:
      BACKUP_PRUNING_PREFIX:
      BACKUP_RETENTION_DAYS:
      AWS_S3_BUCKET_NAME:
      AWS_S3_PATH:
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /opt/docker/dropin/docker-volume-backup/notifications.tpl:/etc/dockervolumebackup/notifications.d/template.tpl:ro
      - db-data:/backup/db-data:ro
      - drupal-files:/backup/drupal-files:ro
      - drupal-private:/backup/drupal-private:ro

volumes:
  db-data:
  drupal-files:
  drupal-private:


networks:
  traefik:
    external: true
  internal:
    external: false