<?php

/**
 * @file
 * Contains brms_revisions.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_form_BASE_FORM_ID_alter().
 */
function brms_revisions_form_node_form_alter(
          &$form, 
          \Drupal\Core\Form\FormStateInterface $form_state,
          $form_id){
  if(($form['revision']['#access']==TRUE)){
    // ensure people cannot uncheck the revision requirement
    $form['revision']['#attributes']['disabled']=true;
    $form['revision']['#value']=true;
    
    // change revision log status based on revision checkbox
    $form['revision_log']['#states'] = [];
    $form['revision_log']['#required']=true;
    $form['revision_log']['widget']['#required']=true;
    $form['revision_log']['widget'][0]['#required']=true;
    $form['revision_log']['widget'][0]['value']['#required']=true;
  } 
}

